Proposals list
lcnem/cosmoscan pull request #100
Opened 2021-08-13 09:09 UTC by Senna46

一旦、Proposalsを一覧表示するためにGov Moluleを作成、サイドメニューも有効化
Proposalsをテストするためにはどのようにすれば良いでしょうか？Proposalファイルを作成してテストノードに投げる以外の方法はないでしょうか？

全proposalsを取得し、proposal_id、statusを表示させようとしています。
![proposals](https://user-images.githubusercontent.com/29295263/129333850-87e19794-0010-4bdc-b47e-4b829a68552b.PNG)

2021-08-16 07:54 UTC, KimuraYu45z requested changes

2021-08-16 07:54 UTC, KimuraYu45z commented on projects/cosmoscan/config.js.template
> +  websocketURL: `${location.protocol.replace('http', 'ws')}//${location.hostname}:16657`,
なんかwebsocket対策の作業がcommitに混入しているような

2021-08-17 05:45 UTC, Senna46 commented
websocket対策作業の混入を修正しました。
#99 も同様に修正したのでレビューお願いします。

![proposals02](https://user-images.githubusercontent.com/29295263/129669804-54a51d2b-f680-457c-bfc9-5f98ccb9348c.PNG)

適当なProposalを投げてみましたが表示までOKです。

2021-08-17 05:45 UTC, Senna46 commented
詳細画面は今取り掛かってます

2021-08-17 05:46 UTC, KimuraYu45z approved these changes
LGTM!

2021-08-17 06:11 UTC, merged