Config
lcnem/cosmoscan pull request #29
Opened 2021-07-03 12:30 UTC by KimuraYu45z

あとはcosmos-sdk.serviceやその他昨日時点でconfig参照してた箇所をこのConfigService使うように変えれば万事解決だと思います！

すべてビルドしたあとでもこのassets/config.js書き換えるだけで設定が変わります。しかもファイル配置なのでdockerのvolume設定しとけばdockerイメージ変更の必要もなく便利かと。

2021-07-03 12:30 UTC, KimuraYu45z commented
botanyリポジトリのcosmoscan extensionでも同様作業が必要です。

2021-07-03 13:57 UTC, YasunoriMATSUOKA requested changes
アドバイス＆プルリク作成ありがとうございます。
まだ実際に動作させてデバッグできていないのですが、コメント入れた箇所は違和感があったため、明日、該当箇所を修正して全体的に再度デバッグして、必要な修正等あれば、こちらからも修正コミット入れさせて頂ければと思います。

2021-07-03 13:57 UTC, YasunoriMATSUOKA commented on projects/cosmoscan/config.js.template
> +  restURL: `${location.protocol}//${location.hostname}:1317`,
詳細は明日以降こちらでもデバッグ試みようと思っていますが、記録として気になった点に一旦コメント残しておきます。

```ts
誤？: restURL: `${location.protocol}//${location.hostname}:1317`,
正？: restURL: `${location.protocol}://${location.hostname}:1317`,
```

2021-07-05 02:00 UTC, YasunoriMATSUOKA requested changes
@KimuraYu45z 
websocketURLの箇所で:を消しておく必要があると思うので、こちらでその部分だけ修正のコミットを入れて、マージしてしまおうと思います。もう少々お待ちください。

2021-07-05 02:00 UTC, YasunoriMATSUOKA commented on projects/cosmoscan/config.js.template
> +  websocketURL: `${location.protocol.replace('http', 'ws')}://${location.hostname}:26657`,
:を削除する必要あり。

2021-07-05 02:13 UTC, YasunoriMATSUOKA commented on projects/cosmoscan/config.js.template
> +  websocketURL: `${location.protocol.replace('http', 'ws')}://${location.hostname}:26657`,
修正しました。

2021-07-05 02:14 UTC, KimuraYu45z commented on projects/cosmoscan/config.js.template
> +  websocketURL: `${location.protocol.replace('http', 'ws')}://${location.hostname}:26657`,
ありがとうございます！

2021-07-05 02:14 UTC, YasunoriMATSUOKA approved these changes
LGTM

2021-07-05 02:23 UTC, KimuraYu45z commented
CI落ちてるとこだけすぐ直しておきます。

2021-07-05 02:25 UTC, KimuraYu45z commented
あ、ありがとうございますｗ

2021-07-05 02:26 UTC, YasunoriMATSUOKA commented
あ、すれ違い...
あってるでしょうか？

2021-07-05 02:26 UTC, KimuraYu45z commented
いえやろうとしてたこと一字一句違わず完全一致でしたｗありがとうございます！

2021-07-05 02:44 UTC, YasunoriMATSUOKA commented
@KimuraYu45z 
buildは通るようになったので、いったんこれでマージして進もうと思いますがOKでしょうか？
(testが通らないのはどこかで別途対応しようと思います。)

2021-07-05 02:45 UTC, KimuraYu45z commented
はい、お願いします！

2021-07-05 02:46 UTC, merged