feat: send github action trigger to botany
lcnem/cosmoscan pull request #67
Opened 2021-07-09 08:52 UTC by Senna46

@YasunoriMATSUOKA 
#53 を実装してみました。
Botanyも合わせてPL作成しています。
一点、APIが`https://api.github.com/repos/lcnem/botany/dispatches`で合っているのか分からないです。

2021-07-09 09:40 UTC, YasunoriMATSUOKA requested changes
@Senna46 
来週詳細説明しますので、修正お願いします。

2021-07-09 09:40 UTC, YasunoriMATSUOKA commented on .github/workflows/docker-cosmoscan.yml
> +    steps:
@Senna46 
先ほど口頭で会話した修正を試みていただきありがとうございます。
ここの記述は不要で、直前のjobの中で、そのままcurlコマンド叩いて良いかな？と思いました。
必要に応じて来週詳細を説明します。

2021-07-13 07:11 UTC, Senna46 commented
@YasunoriMATSUOKA こちらはCreate GitHub dispatch eventするだけなので、これで大丈夫かと思います。

2021-07-13 07:13 UTC, YasunoriMATSUOKA commented on .github/workflows/docker-cosmoscan.yml
> +    steps:
@Senna46 
修正OKです。
ありがとうございました。

2021-07-13 07:15 UTC, YasunoriMATSUOKA approved these changes
LGTM!
マージして、リリースして、一旦エラーが出ないかどうか試してみてください。
エラー出ないようであれば、lcnem/botany側のこれとセットの修正が完了次第、意図通り動作するか試してみてください。

2021-07-13 07:15 UTC, merged