feat: delegator eaning
lcnem/cosmoscan pull request #83
Opened 2021-07-21 06:03 UTC by Senna46

close #77

バリデーター報酬をvestingコンテナに移し、stakingコンテナにデリゲーター報酬を記述し、表示させてみました。
デリゲート先が自身のアドレスしかないのですが、これは問題ないのでしょうか？

![del](https://user-images.githubusercontent.com/29295263/126438696-1ef3b932-e431-485d-8180-8026940f125b.PNG)

@YasunoriMATSUOKA @KimuraYu45z レビューお願いします。

2021-07-21 06:35 UTC, KimuraYu45z commented
デリゲート先が自身、これは正しいです

2021-07-21 08:05 UTC, YasunoriMATSUOKA commented
@Senna46 
pullしてng serveして、以下URLを試しに開いてみたのですが、一部の通信でエラーが発生しているようでした。(もし大村さんの手元ではエラー出ないようなら、自分の手元の環境の問題の可能性もあるかもしれないので、ご連絡頂けると助かります。)
http://localhost:4200/accounts/jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt

エラーが発生している通信

```
polyfills.js:1 GET http://a.test.jpyx.lcnem.net:1317/cosmos/staking/v1beta1/validators/jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt/delegations?pagination.key=jpyxvaloper10lcj22kzftvnduchatmnsnhfljeky5ghh3zpgf 400 (Bad Request)
```

念のため、上記確認してもらえると助かります。(表示は問題なさそうだったので、問題ないのかも？とも思ったのですが、cosmos-client-tsの使い方やcosmos-client-tsの実装を修正する必要はないかを念のためご確認頂けると助かります。)

@KimuraYu45z 
上記コメント違和感あればフォロー頂けると助かります。
また、Validator, Delegatorの報酬について、以下のような理解であっているでしょうか？
自分自信の理解が曖昧であるように感じたため、お手数ですが、念のため、質問させてください。

Validator

- Accumulated Commission ... Validatorがもらえる報酬のうち、支払われたGAS代(≒手数料)分も含む全報酬という理解であっているでしょうか？
- Outstanding Rewards ... 日本語直訳すると抜群の利益？的な言葉に見えるのですが、理解できていないように思います。支払われたGAS代以外(≒手数料)分以外の報酬でしょうか？
- (Slash) ... 現時点では表示していないですが、Slashingで没収された数量をAPIで取得しているでしょうか？(このプルリクではさておき、どこかに表示したほうが良い情報でしょうか？)

Delegator

- Rewards ... Delegatorがもらえる報酬としては、ValidatorのAccumulated CommissionやOutstanding Rewards等のような複数の種類はなく、一種類のみという理解で正しいでしょうか？また、アカウント画面へ表示するDelegatorの報酬の表示としては、Validatorのアカウント画面への表示の場合について、Validatorに委任している全Delegatorの情報を表示するのではなく、Validatorが自分自信へdelegateしているValidator自信のDelegatorアカウントのアドレスのDelegator報酬のみを表示するような形で問題ないでしょうか？

2021-07-21 08:18 UTC, YasunoriMATSUOKA requested changes
@Senna46 
ソースコードの関連すると思う箇所にコメント残しておきました。コメントは推測なので、間違っているかもしれず、確認頂けると助かります。

@KimuraYu45z 
後で相談させてください。

2021-07-21 08:18 UTC, YasunoriMATSUOKA commented on projects/cosmoscan/src/app/accounts/account/vesting/vesting.component.ts
> +      mergeMap(([sdk, accAddress, valAddress]) => rest.cosmos.distribution.validatorSlashes(sdk.rest, valAddress, '1', '2')),
@Senna46 
通信が失敗しているのは、ここなのかな...と推測しています。(未確認なので、確認して頂けると助かります。)
このSlashing関連の値は、今のところ表示では使っていないものの、Slashingの情報はいずれ表示する必要が出そうな気がしているので、いったんコメントアウトしたり消したりしておくか、この機会に修正しておくか、そもそもエラーになりうるものとして何らかの例外処理を書いておくべきか、ちょっと迷っています。

@KimuraYu45z 
後で確認させてください。

2021-07-21 08:30 UTC, Senna46 commented on projects/cosmoscan/src/app/accounts/account/vesting/vesting.component.ts
> +      mergeMap(([sdk, accAddress, valAddress]) => rest.cosmos.distribution.validatorSlashes(sdk.rest, valAddress, '1', '2')),
@YasunoriMATSUOKA 
現時点ではSlashingのAPI`validatorSlashes`とデリゲーターアドレスを指定して、バリデーター報酬を表示するAPI`delegationRewards`関連箇所をコメントアウトしたところ、エラーが消えたので、今回実装した部分はエラーなしで大丈夫かと思います。
この2つは今後表示に追加する可能性がありますが、現状コメントアウトで問題ないですかね？

2021-07-21 08:36 UTC, YasunoriMATSUOKA commented on projects/cosmoscan/src/app/accounts/account/vesting/vesting.component.ts
> +      mergeMap(([sdk, accAddress, valAddress]) => rest.cosmos.distribution.validatorSlashes(sdk.rest, valAddress, '1', '2')),
@Senna46 
一旦、コメントアウトしたソースを同ブランチにプッシュしてみてもらえますでしょうか？

@KimuraYu45z 
現時点で表示に使っていないデータを取得する通信箇所でエラーが発生しているようでした。暫定的にコメントアウトしておき、別途後程対応する形で進めようと思っているのですが、問題ないでしょうか？
念のため、確認させてください。

2021-07-21 09:03 UTC, YasunoriMATSUOKA requested changes
@Senna46 
改めてレビューして気になった点をコメント追加しました。
また来週、ご確認よろしくお願いします。

2021-07-21 09:03 UTC, YasunoriMATSUOKA commented on projects/cosmoscan/src/view/accounts/account/staking/staking.component.html
>  </mat-card>
@Senna46 
おそらく、もともとは、この箇所で、eachrewardsのデータを用いて、accAddressのアカウントがvalAddressを持ちvalidatorとして複数のdelegatorから委任を受けている場合、各delegator毎のdelegator報酬を表示する予定だったのかなと推測しています。

しかし、現時点では、eachrewardsのデータ取得でエラーが発生しており、(代わりに？、)totalrewardsのデータから報酬とアドレスを表示しているように思います。

最初説明を受けたとき、こちらが理解できておらず、これでよいのでは？という回答をしてしまったように思うのですが、改めて考えて、これは矛盾があるように感じたので、このセクションはngIfで有効なeachrewardsが受け取れない場合は丸ごと非表示にするような実装を加えるか、いったんコメントアウトしておくのが望ましいのではないかと思ったのですがいかがでしょうか？

@KimuraYu45z 
上記、違和感あればフォロー頂けると助かります。

2021-07-26 11:31 UTC, Senna46 commented on projects/cosmoscan/src/view/accounts/account/staking/staking.component.html
>  </mat-card>
@YasunoriMATSUOKA 
この箇所ではvaladdressを指定してrewardを取ってくるAPI delegationReward（eachrewards）を使用予定でした。複数のdelegatorからではなく、複数のvalidatorに委任している場合のAPIと推測しています。
[https://v1.cosmos.network/rpc/v0.42.6](https://v1.cosmos.network/rpc/v0.42.6)

現時点では2-12行目 Total Rewardsにて`/accounts/{Accaddress}`から委任しているすべてのデリゲート報酬を表示し、その後、14行目以降 Rewards by Each Validatorでは同じAPIで取得できる、委任先のValaddress別のデリゲート報酬を表示しています。
現在は委任先が自分しかないので、1つのみが表示される状態で問題なく、今後、委任先のValaddressが増えた場合でも、そこまで多数になることは考えられず、全ての委任先が表示される今の表示形式で問題ないと思われますので、モトイキで実装したいと思います。

delegationReward（eachrewards）関連のコードに関しては現在はコメントアウトしてますが、今後Valaddress指定での報酬取得は使わなさそうなので削除でも良いかなと思っています。

2021-07-26 12:32 UTC, YasunoriMATSUOKA commented on projects/cosmoscan/src/view/accounts/account/staking/staking.component.html
>  </mat-card>
@KimuraYu45z @Senna46 
申し訳ないのですが、validatorとdelegatorの関係を自分が正確に理解できていないように感じていて、念のため、以下確認させてもらえないでしょうか？(明日、相談させてください。)

1. まず、この理解は正しいでしょうか？
delegatorはvalidatorに自身のアカウントの残高のstakeを委任してdelegatorとしてのrewardを得ることができる。

2. 次に、この理解は正しいでしょうか？
delegatorは複数のvalidatorに自身の単一アカウント内の残高のstakeを分割して委任してdelegatorとしてのrewardを得ることができる。(←大村さんから頂いたコメントから推測すると、cosmosブロックチェーン上では、同一アカウントの残高ベースのstakeを複数の別々のvalidatorへ分割して委任することができるということなのかなと見えているのですが、この理解は正しいでしょうか？)

3. あるいは、次のような事態も想定されているのでしょうか？
delegatorは、あるタイミングまでは、validatorのアカウントAに全残高のstakeを委任していたが、それ以降は別のvalidatorのアカウントBに全残高のstakeを委任することに変更した。結果的に、validatorアカウントAに対する委任により得られたdelegate報酬と、validatorアカウントBに対する委任により得られたdelegate報酬が存在する。

4. 1は間違っていないと思っているのですが、2, 3については確信が持てていません。そして、1, 2, 3ともに正しい場合、UIのTotal Rewardsの箇所と同じデータを用いて、Reward by Each Validatorの値を表示している(←現状そうなっていると理解しているのですが、もし間違っていたらすみません。)と、2や3のような状況によって、複数のValidator毎のdelegate報酬がある場合、表示される情報に矛盾が生じると思うのですが、何か間違っているでしょうか？

(間違っているかもしれませんが、)1～4のような理解のもと、Reward by Each Validatorの箇所について、以下のいずれかの対応が望ましいと感じました。(非表示にする系の対応をしたものは、後程、eachrewardsを正常に取得できるよう修正が必要と思います。)

- 各validator毎のdelegator reward(eachrewards?)を適切に取得して表示するか、
- 各validator毎のdelegator reward(eachrewards?)を適切に取得できない場合非表示にするか、
- いったんReward by Each Validatorの箇所についてコメントアウトする等して無条件に非表示にしておくか　←　優先度的にはいったんこれでよい？

上記が、現時点で、本件に対して感じている印象です。
こちらが勘違いしている内容もあるのではないかと思うので、明日相談させてください。

2021-07-27 00:57 UTC, KimuraYu45z commented
1,2に関しては正しいです。3.に関しては、累積報酬だとそういう恐れがありますがこれは累積報酬じゃなくブロックごとの報酬みたいなものだと思う（距離に対する時速のような、時間微分）ので

4.累積報酬じゃなくブロックごとの報酬みたいなものであれば矛盾は生じないと思います。(異なるブロック間の矛盾情報表示するわけではない)

どのAPIも基本的には最新ブロックのスナップショットを返すので、矛盾するようなAPIはないと思います。

2021-07-27 01:06 UTC, KimuraYu45z commented
累積報酬の可能性もありますが、累積報酬の場合、多分ブロック0からの通算なので、この場合でも矛盾はないと思います。

2021-07-27 01:37 UTC, KimuraYu45z commented
（てか、何ブロックから何ブロックまで、の指定もあったかもしれない）

2021-07-27 03:12 UTC, Senna46 commented
@YasunoriMATSUOKA コメントアウト追記しました。よろしくお願いします。

2021-07-27 03:12 UTC, YasunoriMATSUOKA commented
@KimuraYu45z @Senna46 

> UIのTotal Rewardsの箇所と同じデータを用いて、Reward by Each Validatorの値を表示している

すみません、上記コメントは、松岡の理解が間違っていました。
大村さんと相談させて頂き、以下APIの、totalの中の情報が総計で、rewardsの中の情報が各validator毎のdelegate報酬の一覧であり、それぞれDelegator Rewardsの項目として、現状の実装で適切な箇所に表示できていることを理解しました。
したがって、画面表示や実装は現状のままで問題なく、ソースコード中のeachrewardsは未使用であること、totalrewardsの中に総計だけでなく、各validator毎のdelegate報酬の一覧の情報も含まれることを、コメントとして追記しておくという形で進めさせてもらおうと思います。

Endpoint: `/cosmos/distribution/v1beta1/delegators/{delegator_address}/rewards`
Description: DelegationTotalRewards queries the total rewards accrued by a each validator.

Response Example: 

```json
{
  "rewards": [
    {
      "validator_address": "string",
      "reward": [
        {
          "denom": "string",
          "amount": "string"
        }
      ]
    }
  ],
  "total": [
    {
      "denom": "string",
      "amount": "string"
    }
  ]
}
```

API Reference URL: https://v1.cosmos.network/rpc/v0.42.6

2021-07-27 03:17 UTC, YasunoriMATSUOKA approved these changes
LGTM!
疑問点解消のため色々相談させて頂きありがとうございましたm(__)m

2021-07-27 03:25 UTC, merged